### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by choosen** [kachick/rspec-matchers-power_assert_matchers#89]
Hello, 
this matcher code seems to not be very complicated thing.
Why did you pick MIT license? 
it's kinda blocker for commercial usage. ([rspec-power-assert](https://github.com/joker1007/rspec-power_assert) also has MIT license) 
Ruby, minitest is BSDL

**Comment by kachick** [comment]
Oh, really? As I understand it, the MIT license allows commercial use similar to the BSD 2-clause license.
What is the blocker to your saying `commercial use`?
Are you saying that this should be put into the public domain? Sorry, but I don't have those plans. 🙇‍♂️ 

References

* https://spdx.org/licenses/MIT.html
* https://spdx.org/licenses/X11.html
* https://spdx.org/licenses/BSD-2-Clause.html
* https://spdx.org/licenses/CC0-1.0.html
* [minitest has MIT license](https://github.com/minitest/minitest/blob/95efe7f430fbd2467885099354ded14b3f4a2770/README.rdoc?plain=1#L809-L832)

**Comment by choosen** [comment]
Oh thanks for links and reply.
I thought that MIT is viral like GPL ;) 

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/11080848/227797226-9bb6ecbb-df7e-4df5-b8af-e49531f89872.png">

Cheers !
